import {
  YoutubeIcon,
  FacebookIcon,
  InstagramIcon,
  TwitterIcon,
} from "./assets/Icons";

export const AVAILABLE_LANGS = {
  pl: "pl",
  en: "en",
};

export const DEFAULT_LANG = "pl";

export const socialMediaArray = [
  {
    icon: <FacebookIcon />,
    link: "https://www.facebook.com/muzeumsztuki",
  },
  {
    icon: <YoutubeIcon />,
    link: "https://www.youtube.com/user/MuzeumSztuki",
  },
  {
    icon: <TwitterIcon />,
    link: "https://twitter.com/muzeumsztuki",
  },
  {
    icon: <InstagramIcon />,
    link: "https://instagram.com/muzeumsztuki/",
  },
];

export const techniquesArray = [
  "olej",
  "deska",
  "płótno",
  "fotografia",
  "gips",
  "sztuczny kamień",
  "drewno",
  "thanina",
  "żywica",
  "instalacja",
  "drzeworyt",
  "papier",
  "offset",
  "druk barwny",
  "torba polietylenowa",
  "akwaforta",
  "karton",
  "kamień",
  "ołówek",
  "stal",
  "film",
  "zapis cyfrowy",
  "asamblaż",
  "polistyren",
  "metal",
  "plexi",
  "silnik",
  "zapis analogowy",
  "papier fotograficzny",
  "fotomontaż",
  "fotokolaż",
  "kolaż",
  "album fotograficzny",
  "kserokopia",
  "materiały różne",
  "akwarela",
  "tworzywo sztuczne",
  "dywan",
  "farba",
  "ceramika",
  "juta",
  "akryl",
  "aluminium anodowane",
  "aluminium",
  "płyta plastikowa",
  "ramy aluminowe",
  "szyba",
  "lustro",
  "litografia",
  "heliografia",
  "tektura",
  "serigrafia",
  "dzianina ze sznurka lnianego",
  "gwasz",
  "stelaż z drutu",
  "monotypia",
  "flamaster",
  "bibułka",
  "brąz",
  "plastik",
  "płyta pilśniowa",
  "taśma metalowa",
  "scotch blue",
  "akwatinta",
  "tempera",
  "tkanina",
  "emulsja",
  "dętka",
  "opona",
  "pismo maszynowe",
  "instalacja elektryczna",
  "linoryt",
  "żarówka",
  "nitro",
  "typolitografia",
  "aluminium malowane",
  "pastel",
  "szkło",
  "pianka",
  "włóczka akrylowa",
  "sklejka",
  "technika mieszana",
  "duraluminium",
  "płyta drewniana",
  "drewno polichromowane",
  "tusz",
  "kalka",
  "gips patynowany",
  "granit",
  "poliester kolorowy",
  "drewno fornirowane",
  "klej",
  "śruby",
  "technika własna",
  "terakota",
  "gwoździe",
  "lakier",
];

export const modernityAreas = [
  "muzeum",
  "autonomia",
  "kapitał",
  "maszyna",
  "miasto",
  "postęp",
  "eksperyment",
  "propaganda",
  "emancypacja",
  "rewolucja",
  "katastrofa",
  "ja",
  "norma",
  "tradycja",
];
